#!/usr/bin/env python3
import sys
from urllib.parse import urljoin, quote_plus, urlparse
from html.parser import HTMLParser

GREEN = '\033[32m'
PURPLE = '\033[35m'
RESET = '\033[39m'

class Select:
	def __init__(self):
		self.clear()

	def clear(self):
		self.name = ''
		self.values = set()


class Form:
	enctypes = {'application/x-www-form-urlencoded': 'a', 'multipart/form-data': 'm', 'text/plain': 't'}
	methods = {'get': '?', 'post': ' ', 'dialog': None}

	def __init__(self):
		self.clear()

	def clear(self):
		self.action = ''
		# enctype is ignored if method is get
		self.enctype = ''
		self.method = ''
		self.params = {}
		self.select = Select()

	def __repr__(self):	
		return f'{PURPLE}{len(urls)}{self.enctype}{self.method}{self.action}{RESET}'


class Lb(HTMLParser):
	form = Form()

	def a(attrs):
		if 'href' in attrs and attrs['href']:
			sys.stdout.write(f'{GREEN}{len(urls)}{RESET} ')
			abs_url = urljoin(urls[1], attrs['href'].strip())
			urls.append(abs_url)

	def get_params(attrs):
		if Lb.form.action and 'name' in attrs and attrs['name']:
			value = attrs.get('value')
			name = quote_plus(attrs['name'])
			if Lb.form.params.get(name) is None:
				# Dicts retain insertion order >= 3.7
				Lb.form.params[name] = set()
			Lb.form.params[name].add(quote_plus(value) if value else '')

	def start_form(attrs):
		method = attrs.get('method')
		if method:
			method = method.lower()
		Lb.form.method = Lb.form.methods.get(method, '?')

		if Lb.form.method is None:
			return

		Lb.form.enctype = Lb.form.enctypes.get(attrs.get('enctype'), 'a')

		# if action is not in attrs, use the path of the last url
		# use / if action is None, path of last url is empty, or action is ''
		action = attrs.get('action', urls[0]) or '/'
		Lb.form.action = action.strip()

	def option(attrs):
		if Lb.form.select.name:
			value = attrs.get('value') or ''
			Lb.form.select.values.add(quote_plus(value))

	def start_select(attrs):
		if Lb.form.action and 'name' in attrs and attrs['name']:
			Lb.form.select.name = attrs['name']

	def end_form():
		if Lb.form.action == '':
			return

		# urljoin after so that only relative url is shown to user
		print(Lb.form)
		abs_url = urljoin(urls[1], Lb.form.action)

		data = []
		for name, values in Lb.form.params.items():
			value = ','.join(values)
			data.append(f'{name}={value}')
		data = '&'.join(data)

		urls.append(f'{abs_url}{Lb.form.method}{data}')
		Lb.form.clear()

	def end_select():
		if Lb.form.select.name:
			Lb.form.params[Lb.form.select.name] = Lb.form.select.values
		Lb.form.select.clear()

	def ignore(not_used):
		# don't print between <script> and <style> tags
		Lb.handle_data = lambda s, d: None

	def show():
		# assume data can't be None
		Lb.handle_data = lambda s, d : not d.isspace() and print(d.strip())

	# tag names produced by handle_starttag are assumed to be lowercase
	start_tag2func = {'a': a, 'input': get_params, 'form': start_form,
	'textarea': get_params, 'button': get_params, 'style': ignore,
	'script': ignore, 'option': option, 'select': start_select}

	# tag names produced by handle_endtag are assumed to be lowercase
	end_tag2func = {'script': show, 'style': show, 'form': end_form,
	'select': end_select}

	def handle_starttag(self, tag, attrs):
		# assume attrs can't be None
		Lb.start_tag2func.get(tag, lambda attrs : None)(dict(attrs))

	def handle_data(self, data):
		not data.isspace() and print(data.strip()) # assume data can't be None

	def handle_endtag(self, tag):
		Lb.end_tag2func.get(tag, lambda : None)()

	# bug NotImplementedError: subclasses of ParserBase must override error()
	def error(self, message):
		sys.stderr.write(str(message))

	# ignore MS-word extension syntax: 2 bugs in _markupbase.py
	def parse_marked_section(self, i, report=1):
		return -1

# replace so users can see that something should have been there
#sys.stdin.reconfigure(errors='replace')
input = sys.stdin.readlines()

# last line of input assumed to be last absolute url requested
# current path used to increase len(urls) by 1, making tail work correctly
urls = [urlparse(input[-1]).path, input[-1]]

Lb().feed('\n'.join(input[:-1]))
for i in range(1, len(urls)): # don't print first url (current path)
	print(urls[i], file=sys.stderr)
